<?php

require_once __DIR__ . '/dataSource.php';
require_once __DIR__ . '/report.php';

/**
 * Class to calculate Report
 */
class PaymentReport extends report
{
    /**
     * SQL Query
     */
    const SQL = 'SELECT strftime(\'%m.%Y\',p.create_ts) as date,count(*) as total_payments, sum(p.amount) as total_sum
                 FROM payments AS p
                 LEFT JOIN documents as d ON p.id = d.payment_id
                 WHERE d.id IS NULL
                 GROUP BY strftime(\'%m.%Y\',p.create_ts)';

    /**
     * File name for report
     */
    const fileName = 'result.csv';

    /**
     * DB resource
     */
    public $db;

    /**
     * Method to init DB
     */
    public function initData()
    {
        $dataSource = new dataSource();
        $dataSource->loadFixtures();
        $this->db = $dataSource->getDatabaseConnection();

    }

    /**
     * Method to create report about payments
     */
    public function createReport()
    {
        $query = $this->db->query(self::SQL);

        while ($row = $query->fetch()) {
          $this->data[] = [ $row['date'],$row['total_payments'], $row['total_sum']];
        }

    }

    /**
     * Method to print report result
     *
     * @param string $template
     */
    public function printResult(string $template)
    {
        parent::printResult($template); // TODO: Change the autogenerated stub

        $fp = fopen(self::fileName, 'w');

        foreach ($this->data as $row) {
            fputcsv($fp, $row, ';');
        }
        fclose($fp);

        $this->downloadFile();
    }

    /**
     * Download file
     */
    public function downloadFile() {
        $path= __DIR__ . '/'.self::fileName;
        $file = ($path);
        header ("Content-Type: application/octet-stream");
        header ("Accept-Ranges: bytes");
        header ("Content-Length: ".filesize($file));
        header ("Content-Disposition: attachment; filename=".$file);
        readfile($file);
    }




}